# Generated by Django 5.2.1 on 2025-05-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_property_roomsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsize',
            name='size',
        ),
    ]
