# Generated by Django 5.2.1 on 2025-05-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='room_images',
            field=models.JSONField(default=list),
        ),
    ]
