# Generated by Django 5.2.1 on 2025-05-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_property_room_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
