# Generated by Django 5.2.1 on 2025-05-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_property_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner_name',
        ),
    ]
