# Generated by Django 5.2.1 on 2025-05-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_property_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
