# Generated by Django 5.2.1 on 2025-06-11 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_propertyrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertyrequest',
            unique_together={('tenant', 'property')},
        ),
    ]
