# Generated by Django 5.2.1 on 2025-06-12 06:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_propertyrequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
