# Generated by Django 5.2.1 on 2025-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_property_building_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
