services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn yourprojectname.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
